### ISSUE TITLE
Create a basic HTTP server

### ISSUE THREAD

**Issue by hueniverse** [hueniverse/hueniversity#1]
Let's get started!

First, we need some basic structure: a `lib` folder, a `package.json` file, and an initial `index.js`. Since we will be using **hapi**, we need to include that in the project dependencies.

Second, create a basic **hapi** server on port 8000 which responds to `/version` requests and replies with a simple `{ "version": "0.0.1" }` JSON payload. The version in the response should come from the `package.json` file.

Assignment due: 3/17

Got questions or need help? Post a comment.

**Comment by AdriVanHoudt** [comment]
Maybe a standard way to post PR will be helpful in the future e.g. every PR for this assignment looks like  `[Assignment 1] My PR title`?

**Comment by rodrigo-medeiros** [comment]
@AdriVanHoudt +1

**Comment by hueniverse** [comment]
I'm ok with that. Generally, github links to this issue are enough for me.

**Comment by rutaihwa** [comment]
[ Assignment #1 ] [Basic HTTP server ] (https://github.com/rutaihwa/hueniversity/commit/7d20e56894a13397c7f93747f6c9f385405bc8f9)

**Comment by hueniverse** [comment]
General comments:

- The project structure should follow the same style of every other hapi module. This means `package.json` should include a `main` property that points to either `index.js` or `lib/index.js`. If the project includes a root `index.js`, it must not include any code other than `require('./lib/index.js')`. This makes searching for code easier later as well as keeps the entire application in one spot. I plan to get rid of the root `index.js` file for all the hapi modules I maintain soon as that extra file is useless.
- Most of the submissions had some minors style issues. Pay attention to the empty lines requirement after function declaration as well as not declaring any local variable other than UpperCamelCase required modules and `internals`. See https://gist.github.com/hueniverse/a06f6315ea736ed1b46d for more information.
- While not a worthwhile optimization in this example, there is no reason to have an endpoint that returns a static object response in which that object is constructed every request. The version payload could have been prepared in advance `internals.response = { version: internals.package.version }`.
- If a callback includes an error, check for it! Some of you forgot to check for the error in `server.start(err)`.
- If there is no way to recover from an error and the process should abort, instead of writing custom code to console log it and then exit, just call `Hoek.assert(!err, err)`.
- No need to make up your own `.gitignore`. Just copy it from hapijs/hapi. Also, you only need a root ignore file, not one in every directory.
- When calling a callback interface, better to add `return` before to make it stand out and avoid bugs where the callback is executed and then some more code at an undefined time. In this case, in the handler make sure you call `return reply({ version: internals.package.version });`.

**Comment by hueniverse** [comment]
Some more:
- You pull request is for this repo, not yours. This means that your `package.json` file should reference this URI, not your fork.
- The `package.json` file can be assigned to either an UpperCamelCase variable (`var Package = require('./package.json');`) or to an `internals` variable but not just a module global per the style guide.
- Some of you went the extra mile with your `package.json` files. Nicely done!
- Bonus points for people who included a route `description`. If you did, better to move `handler` inside `config` when present.
- Pay attention to the assignment specifics. Some of you had the wrong port, version, or specified `localhost` for no reason.
- hapi.js uses BSD for all licenses.

As you can see, those submitting early get a more detailed personal code review. I go over the pull request in order and once I make a comment, I reflect it here for everyone else because repeating it over and over again isn't practical. It is important to read the full assignment notes and review your code even if I didn't comment on it. Pretty much every submission had issues.

**Comment by oluoluoxenfree** [comment]
Is the server supposed to be part of internals? May have confused myself.

**Comment by rutaihwa** [comment]
@oluoluoxenfree if I understand correctly, for the first assignment, it was supposed to be a basic server.  It could as well be started as ` server.start() `, I also think that @hueniverse was giving his feedbacks going forward for future works as it will build on this.

**Comment by oluoluoxenfree** [comment]
@rutaihwa Sorry for deleting I meant to edit, thank you!

**Comment by oluoluoxenfree** [comment]
@rutaihwa How did you reference the issue? All I can find is [this](https://help.github.com/articles/closing-issues-via-commit-messages/).

**Comment by AdriVanHoudt** [comment]
@oluoluoxenfree just put any of the keywords and a reference to the issue in the description like `closes #1`

**Comment by oluoluoxenfree** [comment]
@AdriVanHoudt Thank you! 

Sorry for cluttering up the issue with questions, won't happen again.

**Comment by rutaihwa** [comment]
Thanks @oluoluoxenfree I have overlooked that my self, thanks for the question.

**Comment by AdriVanHoudt** [comment]
@oluoluoxenfree np and this is issue is for questions so feel free to ask whatever you want. If you need general Hapi help check out the gitter https://gitter.im/hapijs/hapi

**Comment by muhammad-saleh** [comment]
Thanks a lot for your time and this was very helpful.
But sorry why are we referencing the issues ?

**Comment by AdriVanHoudt** [comment]
It makes it easier to find what PR is related to what issue and vica versa, not so much needed now but helps when dealing with multiple PR's and issues

**Comment by muhammad-saleh** [comment]
okay great #3

**Comment by asalem57** [comment]
#3

**Comment by hueniverse** [comment]
Quick note about `internals`. The idea is not to declare **any** variable on the module global (e.g. the individual file you are working on). This includes the `server` variable most of you declared. While some were getting close to how it should be done with `internals.server`, that's not ideal. I'll modify the master branch to show how I would prefer to do it.

**Comment by AdriVanHoudt** [comment]
@hueniverse thanks for the clarification! How come no example on hapijs.com does this? Because the examples are too trivial?

**Comment by hueniverse** [comment]
@AdriVanHoudt probably because I didn't write them... :-)

**Comment by AdriVanHoudt** [comment]
@hueniverse haha

**Comment by fyockm** [comment]
@hueniverse thanks for the clarification on `internals`.

**Comment by johnmanko** [comment]
I think I committed, PR's, and commented with 'closes #1' correctly.  Can someone confirm?
