### ISSUE TITLE
Chat forum and repo layout

### ISSUE THREAD

**Issue by gyaresu** [hueniverse/hueniversity#103]
Hi Eran
What do you think about enabling [Gitter](https://gitter.im/) for the repo?

It's not Freenode but it does cater to new programmers in its simplicity. (Or is that just because GUI IRC clients have sucked for too long? Which certainly helped drive the uptake of Slack...)

Also. What are your preferences on the layout of the site to enable new people to start from Assignment 1?

Some of the most helpful notes are a couple of pages down a pull request or at the bottom of an Assignment thread. Link to them directly or embed them in the wiki?

And finally, thank you. I just want to let you know how valuable this has been for me.

It's really perfect as an intermediate step between JS fundamentals and the typical advice to just start building something.

This is the _HOW_ to build something that I've always been missing.

Cheers

**Comment by AdriVanHoudt** [comment]
:+1: on the gitter and adding lessons learnt to the wiki

**Comment by AdriVanHoudt** [comment]
@gyaresu btw you can do these things on your own so no actual need to ask Eran ;)

**Comment by anthonyringoet** [comment]
:+1:

**Comment by gyaresu** [comment]
@AdriVanHoudt Gitter's documentation leaves a lot to be desired but I think only a repo owner can create the room.

**Comment by AdriVanHoudt** [comment]
@gyaresu you're right :D oops

**Comment by lvegerano** [comment]
:+1:

**Comment by zoe-1** [comment]
@gyaresu in respect to a informal chat spot.
Possibly we could we just use the hapijs channel on Freenode for chatting? How would Eran feel about that? It could provide advertising for hueniversity if we chat on an already existing channel like hapijs. However, it could disrupt the hapijs channel but every time I am logged into the channel it does not seem like their is a lot of activity.

**Comment by zoe-1** [comment]
@gyaresu There is one important benefit to not using an informal chat spot. 
When we do not use an informal chat spot other people can come later, read our posts, and learn
from our discussion.  

For example, your PR has 65 posts on it right now. Your post is where all the action is :-)
Last night, I read almost all of them.  I learned from the posts.  Your reposted a link https://gist.github.com/hueniverse/a06f6315ea736ed1b46d which I read and reviewed. 
It was helpful. If you removed those posts to informal chat rooms the community would not benefit from them.  

Plus, logging the activity of posts allows the community to sense the pulse of what is going on. 
If all communication was done in informal chat channels the community would feel stagnant.  There may be a lot of communication going on in the channels but it would look like the project was dead.

**Comment by gyaresu** [comment]
@zoe-1 I was like "65 Whaaat?" but you're right, there's some good advice in there.

Someone might even have some advice on a better way to access them from the awkward layout of  "Show outdated diff"

So I think I'm agreeing with you. We just need to link them in the wiki. 

**Note**
Gitter does have archives but they don't _yet_ seem searchable.
If there was a better level of integration and the chat room was repo specific then it might be very useful(?)
https://gitter.im/hapijs/hapi/archives/all

**Comment by hueniverse** [comment]
Gitter room created.
