### ISSUE TITLE
Wiki Discussion

### ISSUE THREAD

**Issue by zoe-1** [hueniverse/hueniversity#105]
How do we develop and manage the wiki?

As @AdriVanHoudt mentioned, 
<pre>
    I think the wiki needs it's own issue to discuss things, right now anyone can edit 
    and there is no real feedback system on it :/
</pre>

I wrote a document describing my thoughts in a gist document.  
https://gist.github.com/zoe-1/a1052051d49fb5bd88c2
What are your thoughts?

**Comment by AdriVanHoudt** [comment]
1. I think there should only be a solution for past assignments. The point is to learn from other's PR's and comments and discussions. 
2. While the assignment is ongoing it would be nice to have a few 'whatch out for these' to catch the most common mistakes
3. The wiki should be linked in the readme and preferably in the assignment(so it doesn't get lost somewhere)
4. There needs to be a standard layout for the wiki, https://github.com/hueniverse/hueniversity/wiki/99.3-Wiki-Plan is a good start (props to @zoe-1) (plz use markup lists and not 1.) :D ) 
For example I edited https://github.com/hueniverse/hueniversity/wiki/3.1-Start to have clear step by step aprouch.

**Comment by gyaresu** [comment]
1. The repo that gets merged will be the solution(?)
2. Encourage people to "Put that in the Wiki" based on Gitter/Freenode chats and in-line code comments(?)
3. Agree. Wiki's bi-rot very quickly.
4. Agree.
 - We **_REALLY_** an informal chat spot. @zoe-1 is editing the wiki as I type and I thought I killed a whole bunch of pages by fixing the numbered list! :wrench:

**Comment by gyaresu** [comment]
#### Projects with great wiki's
https://github.com/showcases/projects-with-great-wikis

**Comment by zoe-1** [comment]
@AdriVanHoudt  and @gyaresu thank you for your feedback.

In respect to @AdriVanHoudt point 1,  I agree.
As a result, I removed the FAQ stuff and put that info on gist, and put links to the gist write ups
in the Assignment3 wiki.  The focus of the wiki should be about the assignments. 

In respect to @AdriVanHoudt  point2, yeah good idea. 

In respect to @AdriVanHoudt  point 3, agree.  

@AdriVanHoudt  point 4: standard layout
I like your example at: https://github.com/hueniverse/hueniversity/wiki/3.1-Start
Do we need more style recommendations? Is the basic template we already have enough for now?
I think we have enough direction to approach Assignment4.

**Comment by gyaresu** [comment]
I just looked at adding the sidebar to the wiki here but it seem to be an owner-only thing.

And it's a lot easier to edit locally but then I can't push to the wiki repo.

It seems to be a 'thing' so now I'm wondering if creating a submodule and doing a pull request is the best way to do it.

I'd much rather just have \[[Page Names\]] in the "Pages" menu and the sidebar as the main menu.

https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

Ask @hueniverse to create an editable sidebar?

**Comment by zoe-1** [comment]
@gyaresu I agree with you the sidebar https://github.com/guard/guard/wiki is really nice.

@gyaresu in respect to a informal chat spot.
Possibly we could we just use the hapijs channel on Freenode for chatting? How would Eran feel about that? It could provide advertising for hueniversity if we chat on an already existing channel like hapijs. However, it could disrupt the hapijs channel but every time I am logged into the channel it does not seem like their is a lot of activity.

**Comment by gyaresu** [comment]
@zoe-1 I'm personally fine with using #hapi on Freenode.
The other option is: https://gitter.im/hapijs/hapi because it may contain less trolls?
They have an IRC gateway also: https://irc.gitter.im

(Part of me is really against moving away from Freenode though as it's been home for so long)

**Comment by zoe-1** [comment]
@gyaresu There is one important benefit to not using an informal chat spot. 
When we do not use an informal chat spot other people can come later, read our posts, and learn
from our discussion.  

For example, your PR has 65 posts on it right now. Your post is where all the action is :-)
Last night, I read almost all of them.  I learned from the posts.  Your reposted a link https://gist.github.com/hueniverse/a06f6315ea736ed1b46d which I read and reviewed. 
It was helpful. If you removed those posts to informal chat rooms the community would not benefit from them.  

Plus, logging the activity of posts allows the community to sense the pulse of what is going on. 
If all communication was done in informal chat channels the community would feel stagnant.  There may be a lot of communication going on in the channels but it would look like the project was dead.

**Comment by zoe-1** [comment]
@gyaresu I moved the chatroom comments to your chatroom forum issue. 
Could you move your's to there too.  That way we can keep this issue focused on the wiki. 
Thanks ;-)

**Comment by gyaresu** [comment]
@zoe-1 Great. Good to stay on topic.

**Comment by zoe-1** [comment]
Just started a wiki style guide: https://github.com/hueniverse/hueniversity/wiki/Wiki-Style-Guide
This is a working document based on discussion made here in this issue. 
Please check it out.  Hopefully, it will cause more discussion and help us develop a solid style guide.

**Comment by zoe-1** [comment]
I would like this wiki not just be a resource for us but also a resource for people who discover hueniversity months later.  I hope it will be a place others can come and be guided through studying
all assignments of hueniversity at their own pace. 

For example, a person could read the objectives of any assignment and decide if they want to study it.  
Then, they would then be shown what commit to checkout in the repo and begin there. 
The study guide would then explain how to complete the assignment, give links to other PRs illustrating how to complete the assignment, and review important concepts to be understood to complete it.  

This is similar to how the angularjs tutorial is structured. 
See https://docs.angularjs.org/tutorial/
It works well.

What do you think?  Is this too ambitious?

**Comment by EvanMarkHopkins** [comment]
this repo has a guides folder, could recaps go there as well?
