### ISSUE TITLE
Create a sidebar for the wiki

### ISSUE THREAD

**Issue by gyaresu** [hueniverse/hueniversity#106]
We would like to organise a wiki sidebar menu structure similar to [Guard wiki](https://github.com/guard/guard/wiki) but only the project owner can create it.

Github Docs: [Wiki / Creating a sidebar](https://help.github.com/articles/creating-a-sidebar/)

**Comment by AdriVanHoudt** [comment]
:+1:

**Comment by hueniverse** [comment]
If someone posts the content I'll create it. Can others edit it after it is created?

**Comment by gyaresu** [comment]
It looks like it. 
https://github.com/guard/guard/wiki/_Sidebar/_edit

I was even trying to pull a wiki (it's separate apparently) and PR back that way. No joy.

So if it's created I think we can sort it from there. 

I had some ideas for layout but even a simple one will let us collab on it.

(code for me being busy for the next couple of hours. If no-one else responds I'll throw something together)

**Comment by hueniverse** [comment]
Done.
