### ISSUE TITLE
ES6 integration?

### ISSUE THREAD

**Issue by pruett** [hueniverse/hueniversity#11]
I'm curious about the conversation around es6 and if we should integrate that into this "tutorial". I understand that the main goal is to learn Hapi but still very interested in a workflow that allows for ES6 either through io.js or a node.js equivalent approach.

**Comment by AdriVanHoudt** [comment]
well since hapi doesn't officially support io.js I don't think this will be added

**Comment by hueniverse** [comment]
I think we should avoid it for now. Goal is to make this work with node 0.10 for the time being.
