### ISSUE TITLE
Parallel test execution

### ISSUE THREAD

**Issue by tielur** [hueniverse/hueniversity#116]
Shouldn't the parallel option set [here](https://github.com/hueniverse/hueniversity/blob/master/test/index.js#L41) be false? Lab's default for parallel execution seems to be false but I think the point was to explicitly mark this one as basically not safe for parallel execution if we change the default for the tests to parallel in the future.

As noted [here](https://github.com/hueniverse/hueniversity/issues/79#issuecomment-93561251):
> When monkey patching code in a test, mark that test with the { parallel: false } lab option to make it both safe for future parallel testing as well as visual cue.

**Comment by hueniverse** [comment]
Yep. I got distracted with other things after I merged it. Master should be up to date now.
