### ISSUE TITLE
Assigment 1 : Do I need to use a stream ? 

### ISSUE THREAD

**Issue by roelof1967** [hueniverse/hueniversity#17]
Hello, 

I wonder if I need a stream to read the contents of the version  of the package.json or are there better ways to do this ? 

Roelof

**Comment by TheAlphaNerd** [comment]
I read the package.json fwiw

**Comment by roelof1967** [comment]
sorry I do not understan what you mean ?

**Comment by TheAlphaNerd** [comment]
require(‘./package.json');

**Comment by adrianblynch** [comment]
You can simply require the package file `var pkg = require('./package.json')` or read it:

```
fs = require('fs');
fs.readFile(file, [encoding], [callback]);
```

I prefer the former.

**Comment by roelof1967** [comment]
oke, I think this exercises are too difficult for me. If I use the require I still do not have a clue how to read the contents :(

**Comment by muhammad-saleh** [comment]
I did it that way :)
I just read the file content and saved it to a variable
```
var packageJSON = require('./package.json');
```
Now I have an object with the content of the file and you can simply access them like:
```
packageJSON.version
```
Hope I helped

**Comment by TheAlphaNerd** [comment]
when you require a .json file it turns that file into an object.  A great way to figure out this type of stuff is to just try console logging the result, and seeing what it is.

Please do not be discouraged, I promise that you can do it!

**Comment by hueniverse** [comment]
@roelof1967 you have a few options:
- ask (like you did) and get back to trying
- look at what other people submitted, and learn from their code
- do your best and you'll get feedback once submitted
- all of the above :-)

**Comment by roelof1967** [comment]
Im trying now. 

I have now this :+1: 

~~~

var Hapi = require('hapi');
var package = require('./package.json')

var server = new Hapi.Server();

server.connection({ 
  port: 3000 
});

server.route({
    method: 'GET',
    path: '/{version}',
    handler: function (request, reply) {
        reply(package);
    }
});

server.start(function () {
    console.log('Server running at:', server.info.uri);
});

~~~

but that do not give back the answer. So again back to the drawing table. 

Roelof

**Comment by roelof1967** [comment]
When I change it to this : 

~~~
server.route({
    method: 'GET',
    path: '/{version}',
    handler: function (request, reply) {
        reply(package.version) ;
    }
});

~~~

I see the right output but not in json. Also JSON.parse does not turn it into the right answer,
Someone a tip ?

**Comment by muhammad-saleh** [comment]
Try this:
```
reply({ version: package.version })
```

**Comment by roelof1967** [comment]
Thanks, then I have solved this one.

**Comment by adrianblynch** [comment]
@roelof1967 - Take a second look at your path which is `path: '/{version}'`. Read the assignment again and you should spot what's wrong.

What URL are you making the request on?

**Comment by roelof1967** [comment]
Thanks, I solved it already. See my commit
