### ISSUE TITLE
Basic Linting / Testing

### ISSUE THREAD

**Issue by TheAlphaNerd** [hueniverse/hueniversity#4]
It is suggested that individuals follow the hapi style guide while working on this project. It was also suggested that we might want to expand upon our projects by doing things such as writing tests.

My current stack involves eslint + jscs + tape. That being said I know that the hapi project uses lab.

Would it make sense to add a basic pass at lab into our first lesson or is this planned to come in as a separate lesson on testing? I mostly don't like writing any code without some sort of sanity check, but don't want to derail a future lesson plan.

**Comment by hueniverse** [comment]
Adding tests will come shortly after.
