### ISSUE TITLE
JsHint file for styleGuide?

### ISSUE THREAD

**Issue by sfabriece** [hueniverse/hueniversity#66]
Can someone provide a jshint file for the styleGuide for us newbies?

**Comment by benhalverson** [comment]
@sfabriece Here's an example:
{
  "bitwise": true,
  "camelcase": true,
  "curly": true,
  "eqeqeq": true,
  "forin": true,
  "immed": true,
  "indent": 2,
  "latedef": "nofunc",
  "newcap": true,
  "noarg": true,
  "noempty": true,
  "nonbsp": true,
  "quotmark": "single",
  "undef": true,
  "unused": true,

  "strict": true,
  "debug": true,
  "validthis": true,
  "esnext": true,

  "node": true,
  "devel": true,
  "browser": true,
  "jquery": true,

  "globals": {"angular":true, "_":true, "moment":true}
}

**Comment by hueniverse** [comment]
The lab module comes with a built-in rules file. It could be made better but that's the place you want to invest your efforts.

**Comment by AdriVanHoudt** [comment]
I prefer eslint an also direct link ;) https://github.com/hapijs/lab/blob/master/lib/linters/eslint/.eslintrc
