### ISSUE TITLE
100% coverage

### ISSUE THREAD

**Issue by hueniverse** [hueniverse/hueniversity#79]
Things are getting a bit more interesting...

It's time to add tests, verify coverage, confirm style, and automate all of this with CI. We will be using the [lab](https://github.com/hapijs/lab) module to perform all these tasks and automate it with [travis](https://travis-ci.org).

1. Add a `.travis.yml` file, testing our project on node 0.10, 0.12, and io.js (latest).
2. Add a test folder with two files, `version.js` and `index.js`, each testing the corresponding file under `/lib`.
3. Modify the `package.json` file to include the tests, as well as the dev dependency to lab.
4. Add the standard hapi.js Makefile to make it easy to generate other types of reports (e.g. HTML coverage report).
5. When using lab, enable coverage, require 100% coverage, enable linting with default rules, and use the [code](https://github.com/hapijs/code) assertion library.
6. Write a basic test to verify our version endpoint in `version.js`.
7. Change the `init()` method to accept a port and a callback. Use the callback to return when the function completes or errors. The `init()` callback should return any error state as well as a reference to the newly created server. This will allow us to later stop the server when we test it.
8. Export `init()` and move the invocation to a new `start.js` file (which will call the `init()` function with the `8000` port and a callback the outputs the information to the console when started). Change the `package.json` file to use the `start.js` file as the starting place. This file will not be covered by tests.
9. Write a basic test to verify the `init()` function in `index.js`.
10. Bring coverage to 100% by adding more tests as needed.

Everything up to (10) should be pretty straight forward. If you are not sure on how to use lab and code, look at other hapi.js modules like hoek, qs, items, and boom (e.g. simple modules) to copy their test scripts and setup.

Getting 100% coverage can be tricky sometimes so if you are not sure, get as much coverage as you can, and comment on the lines in your pull request where you are having a hard time reaching and someone will give you a clue.

Remember to properly `stop()` your servers when calling the `init()` method in each test.

For now, avoid using any of the `before()` and `after()` lab features.

As always, ask for help and help others!

Due: 4/4

**Comment by AdriVanHoudt** [comment]
Wasn't there a general agreement(if you want I'll search for the issue in question) to use npm for all the different tests as in define them in package.json instead of a Makefile?

**Comment by hueniverse** [comment]
1. Fixed.
2. The makefile gives you easy access to stuff like `make cov-html` while the package.json one is for `npm test`.

**Comment by AdriVanHoudt** [comment]
1. Ok but you still declare the response in internals, why?
2. you can easily run `npm run cov-html` plus it works also on Windows

**Comment by hueniverse** [comment]
The response is in internals so you don't create the object on every request. It's a small optimization.

**Comment by TheAlphaNerd** [comment]
I'm a bit stuck with the logic of testing when no arguments are given to init.  Specifically I am curious the best practice on what init should return.  If init does not return the server then there is no way to shut it down in testing without using something for spying.

For right now I have opted to return the server, it is gross but hopefully it will work for now

**Comment by hueniverse** [comment]
@TheAlphaNerd did you notice the steps above to modify the `init()` method?

**Comment by TheAlphaNerd** [comment]
Indeed.  You specifically state ``` If no callback is provided, assert on errors.```

I think I managed to figure out how to get that to work as expected with coverage.  The only thing I'm stuck on now is figuring out how to test specific error states that we will be executing the callback from.

For example how do I write a test that guarantees the plugin will load with an error.

**Comment by TheAlphaNerd** [comment]
It is worth mentioning that the solution I found was returning the server object when no callback is provided.  What confused me specifically was how to properly stop the server if not callback was provided

**Comment by hueniverse** [comment]
I have changed the assignment (step 7 and 8) to avoid the problem you hit. Sorry about that.

**Comment by AdriVanHoudt** [comment]
@hueniverse I can see the optimization but does it weigh up against less readability? Also last thoughts on the makefile?

**Comment by TheAlphaNerd** [comment]
@hueniverse one more quick clarification.  Do we want to call ```server.start()``` in start.js or lib/index?

**Comment by hueniverse** [comment]
Leave `server.start()` in `init()`.

**Comment by towns** [comment]
What about the travis integration? Do we need to set that up? I have added the travis.yml file, but do I need to configure my project in Travis to verify that I have automated this properly?

**Comment by TheAlphaNerd** [comment]
the .travis file is all you need!

**Comment by zoe-1** [comment]
Question Regarding Item 8:
The init() callback should return any error state as well as a reference
to the newly created server. This will allow us to later stop the server
when we test it.

I was not quite sure what to do here, so I just followed @TheAphaNerd style.
Then in tests, we just use server.stop() inside init() to stop the server.  
The tests work but the callback() does not return anything (error state or new server object). 
So, I do not think we are satisfying the above requirement. 
What is the best way to do this?

**Comment by rutaihwa** [comment]
Community, I am bit more than stuck starting from point 6, I could use some help to get going.

**Comment by chyld** [comment]
To @zoe-1's point, the code in index.js and version.js should not be throwing any errors, with Hoek, but instead should be sending any errors back to the original caller - which would be either start.js or in the test code.

**Comment by mikejerome** [comment]
Is there a way to have the linter display the filenames where linting errors are found? Mine only shows line numbers but no filenames.

**Comment by hussainanjar** [comment]
@mikeal linter does show both filename and line numbers, see below example output of linter

```bash
Linting results:
	lib/index.js:
		Line 15: semi - Missing semicolon.
	lib/version.js:
		Line 15: no-trailing-spaces - Trailing spaces not allowed.
```

**Comment by mikejerome** [comment]
Hmmm I'm using solarized terminal. The filenames must be the same color as my background or something. I verified that they are there by copy-pasting but they are invisible in my terminal.

**Comment by zoe-1** [comment]
I started a tutorial / wiki for Assignment3.
https://github.com/zoe-1/hueniversity/wiki/3--Assignment
Please check it out. Hopefully, others can look it over, make recommendations, and 
also contribute to a hueniversity wiki for others to learn from :-)

**Comment by chyld** [comment]
Nice work @zoe-1

**Comment by rutaihwa** [comment]
Thanks @zoe-1

**Comment by hueniverse** [comment]
@zoe-1 feel free to put it all directly in this project wiki.

**Comment by zoe-1** [comment]
@hueniverse I put Assignment3 wiki tutorial into this project wiki.  Plus, I made some more edits. 
I manually copied and pasted it into the project.  Is there a way to automate that? kind of like a PR for
a wiki? Thank you for starting hueniversity :-)
Cheers!

**Comment by hueniverse** [comment]
So far we got half the previous number of pull request. If you have submitted a PR before but didn't this time, what's the reason? Is it too hard? Lost interest?

Any feedback would be useful to improve the experiment.

**Comment by TheAlphaNerd** [comment]
I think it is worth considering the fact that while there are less PR's there was quite a bit more activity

**Comment by MrBri** [comment]
I have a love-hate relationship with writing tests. I know its important and it feels good to see the green but the desire to sit down and write them isn't as strong as say creating something new for a user.

**Comment by mikejerome** [comment]
I'm a total noob who has never done testing but I know I need to do it and following along has made it much less intimidating. This is an amazing project and I am learning so much from this experiment. I feel like this is so much more powerful than blog posts or videos.

**Comment by AdriVanHoudt** [comment]
I think the size + difficulty might have to do something with it. The assignment looks bigger, although the actual execution size is not much more than before, just more smaller things. The main thing would be difficulty, the basic tests are fine but getting to 100% cc can be hard (my, and others, solution was to switch out the register function of the version plugin) and to me that doesn't seem like a clean test and also not super straight forward. On the other hand I think the project itself has indeed more activity on it as @TheAlphaNerd says. 
@MrBri I'm not gonna discuss the importance of tests with you but doing some basic ones like in here might help you create some more love for them ;)

**Comment by rutaihwa** [comment]
Just as @AdriVanHoudt when i read the specification, everything seemed so out of my league. As with many programmer who like to hack not to test. But in fact, The entire thing makes alot of sense. Maybe I should adopt this philosopy of starting with tests and then write the actual code.
I think @hueniverse statement: "Everything up to (10) should be pretty straight forward." may have made many some people who were not very sure with the stuff like my self a bit nervous, I guess.

**Comment by AdriVanHoudt** [comment]
also side note, the assignment didn't state where `start.js` needed to go
@rutaihwa good to hear I'm not alone, it comes down to writing style maybe? When reading the assignment it felt like a lot and hard but when broken down it was not to hard as `Everything up to (10) should be pretty straight forward` suggests, although stuff like that does not help insecure devs who might have problems along the way(which is totally fine, we're here to help) and then read that what they are struggling with should be straightforward

**Comment by EvanMarkHopkins** [comment]
On your next pet project, write some tests in advance. Don't strive for 100% coverge right away, but clearly document your agenda. That way the tests are no longer what's standing between you and shipping, it's your life time fitness coach. :stuck_out_tongue_winking_eye:

**Comment by gyaresu** [comment]
I'm a sysadmin who has done a whole bunch of 'learn JS' work and codewars/project euler problems.
Lack of knowledge around the aspects such as the way `lab` works or how to structure the app (cb chain) meant that I am still reading about the pieces rather than using them to build the app.
I'm still following along as this is really valuable but it just might be at a more confused pace.

I don't want to be disingenuous by just copypasta'ing someone elses work.

Thanks to @zoe-1 for the wiki, that moved the challenge from "no clue" to "what to research".

**Comment by hussainanjar** [comment]
@gyaresu this is community based learning, you will still learn better with copy pasting then not doing any thing, its not a competition so no one will be caught for cheating, better advice don't copy paste but try to write code following others pull request if its too difficult for you do it yourself right now.

Though learning and making an honest attempt to do it yourself is the best way to go.

**Comment by AdriVanHoudt** [comment]
Completely true, I tried as mich as I can on my own but for testing the
plugin registration failiour catch I also looked at how other did it

**Comment by zoe-1** [comment]
After reading Assignment3 requirements, I think I understood about 60% of it. (Possibly, many just quit here)  Since I did not understand the whole assignment,  I began to look through PRs for sample code I could learn from.  I studied @TheAlphaNerd's and @chyld's  code the most and read a bunch of documentation. 

After that, I  wrote my own program based on what the above two did, posted my project, and got feedback from others.  Interestingly, the people I modeled my code after critiqued my project :-) 
I learned a ton from this assignment:-)  Thank you to everyone who contributed. 
Hopefully, more people will join and continue with the assignments.  
There is still time to submit a PR!   

@AdriVanHoudt and @hussainanjar are right, we should study other PRs to complete assignments.  If you rely on or use others' work, just give them credit for their influence on your work.  Plus, if you are afraid of copying and not learning while studying someone else's code, just re-type everything and do not copy and paste.  While re-typing the code make sure you understand everything you type.  Look up every command in the docs etc...

**Comment by gyaresu** [comment]
Thanks @zoe-1 I'm attacking it with fresh eyes.

**Comment by zoe-1** [comment]
@gyaresu go for it!

**Comment by hueniverse** [comment]
I've extended the deadline to 4/4 in hopes more people to give it a try. If you are not clear, just look at other pull requests as people above suggested. The way this entire experiment works is by moving the learning from the assignment instructions to the community interaction.

If you do not interact, you will not learn and you will fall behind. We are all teachers here!

**Comment by zoe-1** [comment]
Just made a document called wiki plan.  Hope it sparks some good conversation and planning :-)
https://github.com/hueniverse/hueniversity/wiki/99.3-Wiki-Plan

Additionally, started a section in the wiki called: FAQ and Important issues.
It contains new documents related to: 
1)Makefiles and 2) Modules and Singleton Pattern.
https://github.com/hueniverse/hueniversity/wiki/99-FAQ

Please take a look.

**Comment by AdriVanHoudt** [comment]
@zoe-1 nice work :+1: , I think the wiki needs it's own issue to discuss things, right now anyone can edit and there is no real feedback system on it :/ maybe even worth it to make a separate repo or something for it

**Comment by zoe-1** [comment]
@AdriVanHoudt just made an issue for the wiki.

**Comment by zoe-1** [comment]
Wrote a short explanation of how assignment3 used the singleton objects made with node's required modules. This concept is essential to understand how to avoid exporting values just to pass tests.
See:  https://gist.github.com/zoe-1/d5465682428edc583ccc

Plus, wrote an explanation of why we want to use a Makefile.
https://gist.github.com/zoe-1/784100440f0cf2299010
Hope these help.

**Comment by EvanMarkHopkins** [comment]
I don't think the purpose of a makefile, at least in the context of **this assignment**, was to create an alias to npm commands; We were also asked to use the *standard hapi makefile*, which is pretty specific, and we probably shouldn't go changing its behavior entirely. That being said, you're doing a lot of great work!

**Comment by EvanMarkHopkins** [comment]
Sorry, not entirely changing its behavior, but it certainly seems like it's sidestepping a little. Also, I think the article on singletons is very valuable information, thank you ^_^

**Comment by zoe-1** [comment]
@EvanMarkHopkins thank you for your kind words :-) 

In respect to the Makefile, like you said, hopefully @hueniverse  will explain why he wants it in the project.  Personally, I view it as a convenience for abbreviating commands frequently used. Based on the following hapijs issues https://github.com/hapijs/contrib/issues/14 and 
https://github.com/hapijs/lab/issues/284, it seems that @hueniverse is ok with removing the Makefile and putting everything into npm.  So, I suspect it is used as a convenience and is just a preference of @hueniverse to use. But, that is only my guess.

**Comment by EvanMarkHopkins** [comment]
Okay, I just found it really bizarre. Nothing about it really suggested a preference for interfacing with Make directly over npm, it just seemed like a valid way to organize things. I'm all for removing it. I can see this causing unnecessary confusion.

**Comment by hueniverse** [comment]
Re: makefile - I wanted people to see the two options of setting command shotcuts with npm and make. hapi uses both and the trend is to move away from the makefile and only use npm shortcuts. But I find it useful to have both so that you can see how it's done but also able to find your way around other projects that use either option.

**Comment by AdriVanHoudt** [comment]
@hueniverse thanks for the reaction. I see the purpose of learning to use both but it's ok to let the makefile point to npm in this case right?

**Comment by hueniverse** [comment]
General comments:
- When monkey patching code in a test, mark that test with the `{ parallel: false }` lab option to make it both safe for future parallel testing as well as visual cue.
- Never return anything other than an actual `Error` as an error (e.g. no strings, plain objects, etc.).
- Never use fixed port numbers in tests, only `0` or the default.
- Always `return` before `next()` unless there is a reason to continue.
- Some of you missed the change in the assignment to make both arguments in `init()` required.
- When calling `server.inject()` with a GET request, just pass the path string as the first argument instead of an options object. Makes the code much more readable.
- Use the testing shortcuts boilerplate used in hapi. Makes reading tests easier.

Also, if others are leaving comments on your code, you should either reply or address their suggestions. This experiment works by learning sideways, not just top to bottom. I have seen a lot of great comments from peers, so please respect their time and use it to learn. If I see you ignoring useful comments from others, I am not going to bother adding my own comments.

**Comment by gyaresu** [comment]
:+1:

**Comment by TheAlphaNerd** [comment]
thanks for taking the time!

**Comment by zoe-1** [comment]
Thanks for the feedback :-)

**Comment by gyaresu** [comment]
* Can someone provide an example of the monkey patching that might lead to switching off parallel tests? I don't think I was doing that.
 * Only return `err` :ok:
 * Using `.equal(8000)` in tests. :ok: (I think)
 * Returning the next function: `return next()` :ok: 
 * `exports.init = function (port, next) {` <= That init? from index.js
 * Pass the path string: `server.inject('/version', function(response) {` :ok:
 * Testing shortcuts: 
```var expect = Code.expect;
var describe = lab.experiment;
var it = lab.test;``` :ok:

**Comment by zoe-1** [comment]
@gyaresu 
 
lab docs show how to include the parallel option.
<pre>
lab.test('returns true when 1 + 1 equals 2', { parallel: true }, function (done) {

        Code.expect(1+1).to.equal(2);
        done();
 });
</pre>
source: https://github.com/hapijs/lab
Got the above from the documentation.  Yeah, I did not include it either.

I believe monkey patching would be where we changed the default values
of a plugins methods so it would break.

        Version.register = function(server, options, next) {
            next('Plugin Error');
        };

        Version.register.attributes = {name: 'Fake Plugin'};

**Comment by tielur** [comment]
> Use the testing shortcuts boilerplate used in hapi. Makes reading tests easier.

Is that just the Makefile used in the hapi project?

**Comment by gyaresu** [comment]
@tielur I think it refers to the names you give `lab` and `code` methods.
i.e.
```
var expect = Code.expect; 
var describe = lab.experiment; 
var it = lab.test;
```

**Comment by tielur** [comment]
@gyaresu ahh ok that makes sense. Thanks!

**Comment by gyaresu** [comment]
@tielur I just grabbed your code to have a look and the `npm test` doesn't print out the tests. Mine did that originally and I'm just looking for the advice somewhere in my PR's. (Will update when I find it but thought you'd be interested as we use different tests)

![screenshot 2015-04-15 16 48 39](https://cloud.githubusercontent.com/assets/29263/7171636/e2f6abda-e38f-11e4-9b51-ccf30322f0ea.png)

**Comment by zoe-1** [comment]
@hueniverse commented:
<pre>
Some of you missed the change in the assignment to make both arguments in init() required.
</pre>
I am assuming he wants the parameters in init() to be validated.
Mainly, just test that a valid port was submitted.  
How is everyone else interpreting this?

**Comment by hueniverse** [comment]
The original assignment had the port as optional which meant you had to check if the first argument was a number or a function. This was removed but not everyone got the memo.

**Comment by zoe-1** [comment]
Ok. got it. 
I made tests for the port again.  Will go remove them.

**Comment by tielur** [comment]
@gyaresu it's the `-v` option that you have for lab. It does the verbose test output.

**Comment by gyaresu** [comment]
@tielur Sweet. Thanks.

**Comment by roelof1967** [comment]
I have a error that I cannot solve.,
I deleted this part : 

~~~

internals.init = function () { 
     if (typeof port === 'function') { 

~~~

and changed it to : 

~~~
server.connection({ port: port });

~~~

but now on every test I see a error message that port must be a string, a number. 
How to solve this ?

My code can be found here : https://github.com/roelof1967/hueniversity

**Comment by EvanMarkHopkins** [comment]
@roelof1967 you have tests that are omitting the port

**Comment by roelof1967** [comment]
Thanks, it worked now without any problem. A new PR is submitted already

**Comment by AdriVanHoudt** [comment]
@hueniverse is it beneficial to add `return` before the `done()` calls in every test? I'm not sure if it adds readability. Although I'm personally a fan of it.

**Comment by hueniverse** [comment]
@AdriVanHoudt Nah.

**Comment by AdriVanHoudt** [comment]
@hueniverse could you go into why you choose that PR to merge? Also there is now no way for me t run the tests on my windows :neutral_face:

**Comment by simon-p-r** [comment]
You can install make on Windows, I use https://github.com/lukesampson/scoop which is very good for Windows users.

On 19 Apr 2015 10:00 am, AdriVanHoudt <notifications@github.com> wrote:

@hueniverse<https://github.com/hueniverse> could you go into why you choose that PR to merge? Also there is now no way for me t run the tests on my windows [:neutral_face:]

**Comment by johnmanko** [comment]
So are we creating a Makefile?  Also, when you say "Add the standard hapi.js Makefile" please point to documentation on what that "standard hapi.js Makefile" is and how it should be constructed.  Too many assumptions on what we know what you're talking about.

**Comment by danielb2** [comment]
I suggest this Makefile reference should be removed completely since we're no longer using Makefiles as per https://github.com/hapijs/contrib/issues/31

**Comment by zoe-1** [comment]
@johnmank Below is the answer to your makefile question. 

As referenced in this assignments post:
<b>Note:</b> From [Assignments5](https://github.com/hapijs/university/issues/136) on this project only uses npm. Between assignments 4 and 5, [style rules changed](https://github.com/hapijs/contrib/issues/31) and the Makefile was removed from hapijs projects.
